language: node_js
node_js:
  - 8
script:
  - cd admin
  - npm install
  - npm test
  - npm run build
fail_fast: true
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: car-rent-store
  on: master
